/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.trade.swap;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.collect.ArgChecker;
import com.opengamma.schedule.ScheduleProvider;

/**
 * TODO this is the wrong place for this but will do for now
 */
@BeanDefinition
public class SwapLeg implements ImmutableBean {

  @PropertyDefinition(validate = "notNull")
  private final ScheduleProvider scheduleProvider;

  @ImmutableConstructor
  public SwapLeg(ScheduleProvider scheduleProvider) {
    this.scheduleProvider = ArgChecker.notNull(scheduleProvider, "scheduleProvider");
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code SwapLeg}.
   * @return the meta-bean, not null
   */
  public static SwapLeg.Meta meta() {
    return SwapLeg.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(SwapLeg.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static SwapLeg.Builder builder() {
    return new SwapLeg.Builder();
  }

  @Override
  public SwapLeg.Meta metaBean() {
    return SwapLeg.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the scheduleProvider.
   * @return the value of the property, not null
   */
  public ScheduleProvider getScheduleProvider() {
    return scheduleProvider;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      SwapLeg other = (SwapLeg) obj;
      return JodaBeanUtils.equal(getScheduleProvider(), other.getScheduleProvider());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getScheduleProvider());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("SwapLeg{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("scheduleProvider").append('=').append(JodaBeanUtils.toString(getScheduleProvider())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code SwapLeg}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code scheduleProvider} property.
     */
    private final MetaProperty<ScheduleProvider> scheduleProvider = DirectMetaProperty.ofImmutable(
        this, "scheduleProvider", SwapLeg.class, ScheduleProvider.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "scheduleProvider");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 1427142056:  // scheduleProvider
          return scheduleProvider;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public SwapLeg.Builder builder() {
      return new SwapLeg.Builder();
    }

    @Override
    public Class<? extends SwapLeg> beanType() {
      return SwapLeg.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code scheduleProvider} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<ScheduleProvider> scheduleProvider() {
      return scheduleProvider;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 1427142056:  // scheduleProvider
          return ((SwapLeg) bean).getScheduleProvider();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code SwapLeg}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<SwapLeg> {

    private ScheduleProvider scheduleProvider;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(SwapLeg beanToCopy) {
      this.scheduleProvider = beanToCopy.getScheduleProvider();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 1427142056:  // scheduleProvider
          return scheduleProvider;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 1427142056:  // scheduleProvider
          this.scheduleProvider = (ScheduleProvider) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public SwapLeg build() {
      return new SwapLeg(
          scheduleProvider);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code scheduleProvider} property in the builder.
     * @param scheduleProvider  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder scheduleProvider(ScheduleProvider scheduleProvider) {
      JodaBeanUtils.notNull(scheduleProvider, "scheduleProvider");
      this.scheduleProvider = scheduleProvider;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("SwapLeg.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("scheduleProvider").append('=').append(JodaBeanUtils.toString(scheduleProvider)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
