/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.trade.swap;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.collect.ArgChecker;

/**
 * TODO bean
 * TODO this is the wrong place for this but will do for now
 */
@BeanDefinition
public class SwapTrade implements ImmutableBean {

  @PropertyDefinition(validate = "notNull")
  private final SwapLeg leg1;

  @PropertyDefinition(validate = "notNull")
  private final SwapLeg leg2;

  // TODO should trade info be individual fields (and Trade interface?) or a TradeInfo object shared across trade types?

  @ImmutableConstructor
  public SwapTrade(SwapLeg leg1, SwapLeg leg2) {
    this.leg1 = ArgChecker.notNull(leg1, "leg1");
    this.leg2 = ArgChecker.notNull(leg2, "leg2");
  }
  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code SwapTrade}.
   * @return the meta-bean, not null
   */
  public static SwapTrade.Meta meta() {
    return SwapTrade.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(SwapTrade.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static SwapTrade.Builder builder() {
    return new SwapTrade.Builder();
  }

  @Override
  public SwapTrade.Meta metaBean() {
    return SwapTrade.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the leg1.
   * @return the value of the property, not null
   */
  public SwapLeg getLeg1() {
    return leg1;
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the leg2.
   * @return the value of the property, not null
   */
  public SwapLeg getLeg2() {
    return leg2;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      SwapTrade other = (SwapTrade) obj;
      return JodaBeanUtils.equal(getLeg1(), other.getLeg1()) &&
          JodaBeanUtils.equal(getLeg2(), other.getLeg2());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getLeg1());
    hash += hash * 31 + JodaBeanUtils.hashCode(getLeg2());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(96);
    buf.append("SwapTrade{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("leg1").append('=').append(JodaBeanUtils.toString(getLeg1())).append(',').append(' ');
    buf.append("leg2").append('=').append(JodaBeanUtils.toString(getLeg2())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code SwapTrade}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code leg1} property.
     */
    private final MetaProperty<SwapLeg> leg1 = DirectMetaProperty.ofImmutable(
        this, "leg1", SwapTrade.class, SwapLeg.class);
    /**
     * The meta-property for the {@code leg2} property.
     */
    private final MetaProperty<SwapLeg> leg2 = DirectMetaProperty.ofImmutable(
        this, "leg2", SwapTrade.class, SwapLeg.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "leg1",
        "leg2");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3317731:  // leg1
          return leg1;
        case 3317732:  // leg2
          return leg2;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public SwapTrade.Builder builder() {
      return new SwapTrade.Builder();
    }

    @Override
    public Class<? extends SwapTrade> beanType() {
      return SwapTrade.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code leg1} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<SwapLeg> leg1() {
      return leg1;
    }

    /**
     * The meta-property for the {@code leg2} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<SwapLeg> leg2() {
      return leg2;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 3317731:  // leg1
          return ((SwapTrade) bean).getLeg1();
        case 3317732:  // leg2
          return ((SwapTrade) bean).getLeg2();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code SwapTrade}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<SwapTrade> {

    private SwapLeg leg1;
    private SwapLeg leg2;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(SwapTrade beanToCopy) {
      this.leg1 = beanToCopy.getLeg1();
      this.leg2 = beanToCopy.getLeg2();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 3317731:  // leg1
          return leg1;
        case 3317732:  // leg2
          return leg2;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 3317731:  // leg1
          this.leg1 = (SwapLeg) newValue;
          break;
        case 3317732:  // leg2
          this.leg2 = (SwapLeg) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public SwapTrade build() {
      return new SwapTrade(
          leg1,
          leg2);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code leg1} property in the builder.
     * @param leg1  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder leg1(SwapLeg leg1) {
      JodaBeanUtils.notNull(leg1, "leg1");
      this.leg1 = leg1;
      return this;
    }

    /**
     * Sets the {@code leg2} property in the builder.
     * @param leg2  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder leg2(SwapLeg leg2) {
      JodaBeanUtils.notNull(leg2, "leg2");
      this.leg2 = leg2;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(96);
      buf.append("SwapTrade.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("leg1").append('=').append(JodaBeanUtils.toString(leg1)).append(',').append(' ');
      buf.append("leg2").append('=').append(JodaBeanUtils.toString(leg2)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
