/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.schedule;

import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.opengamma.collect.ArgChecker;

/**
 * Provides a pre-build custom schedule.
 */
@BeanDefinition
public class CustomScheduleProvider implements ScheduleProvider, ImmutableBean {

  @PropertyDefinition(validate = "notNull")
  private final Schedule schedule;

  @ImmutableConstructor
  public CustomScheduleProvider(Schedule schedule) {
    this.schedule = ArgChecker.notNull(schedule, "schedule");
  }
  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code CustomScheduleProvider}.
   * @return the meta-bean, not null
   */
  public static CustomScheduleProvider.Meta meta() {
    return CustomScheduleProvider.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(CustomScheduleProvider.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static CustomScheduleProvider.Builder builder() {
    return new CustomScheduleProvider.Builder();
  }

  @Override
  public CustomScheduleProvider.Meta metaBean() {
    return CustomScheduleProvider.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the schedule.
   * @return the value of the property, not null
   */
  public Schedule getSchedule() {
    return schedule;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      CustomScheduleProvider other = (CustomScheduleProvider) obj;
      return JodaBeanUtils.equal(getSchedule(), other.getSchedule());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getSchedule());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("CustomScheduleProvider{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("schedule").append('=').append(JodaBeanUtils.toString(getSchedule())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code CustomScheduleProvider}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code schedule} property.
     */
    private final MetaProperty<Schedule> schedule = DirectMetaProperty.ofImmutable(
        this, "schedule", CustomScheduleProvider.class, Schedule.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "schedule");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case -697920873:  // schedule
          return schedule;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public CustomScheduleProvider.Builder builder() {
      return new CustomScheduleProvider.Builder();
    }

    @Override
    public Class<? extends CustomScheduleProvider> beanType() {
      return CustomScheduleProvider.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code schedule} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Schedule> schedule() {
      return schedule;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case -697920873:  // schedule
          return ((CustomScheduleProvider) bean).getSchedule();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code CustomScheduleProvider}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<CustomScheduleProvider> {

    private Schedule schedule;

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(CustomScheduleProvider beanToCopy) {
      this.schedule = beanToCopy.getSchedule();
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case -697920873:  // schedule
          return schedule;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case -697920873:  // schedule
          this.schedule = (Schedule) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public CustomScheduleProvider build() {
      return new CustomScheduleProvider(
          schedule);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code schedule} property in the builder.
     * @param schedule  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder schedule(Schedule schedule) {
      JodaBeanUtils.notNull(schedule, "schedule");
      this.schedule = schedule;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("CustomScheduleProvider.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("schedule").append('=').append(JodaBeanUtils.toString(schedule)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
