/**
 * Copyright (C) 2014 - present by OpenGamma Inc. and the OpenGamma group of companies
 *
 * Please see distribution for license.
 */
package com.opengamma.schedule;

import java.util.HashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Optional;
import java.util.Set;

import org.joda.beans.Bean;
import org.joda.beans.BeanDefinition;
import org.joda.beans.ImmutableBean;
import org.joda.beans.ImmutableConstructor;
import org.joda.beans.JodaBeanUtils;
import org.joda.beans.MetaProperty;
import org.joda.beans.Property;
import org.joda.beans.PropertyDefinition;
import org.joda.beans.impl.direct.DirectFieldsBeanBuilder;
import org.joda.beans.impl.direct.DirectMetaBean;
import org.joda.beans.impl.direct.DirectMetaProperty;
import org.joda.beans.impl.direct.DirectMetaPropertyMap;

import com.google.common.collect.ImmutableMap;
import com.opengamma.collect.ArgChecker;

/**
 *
 */
@BeanDefinition
public class FieldMap implements ImmutableBean {

  @PropertyDefinition(validate = "notNull")
  private final Map<FieldKey<?>, Object> map;

  public FieldMap() {
    this(ImmutableMap.of());
  }

  @ImmutableConstructor
  private FieldMap(Map<FieldKey<?>, Object> map) {
    // TODO check the types of the keys and values match
    this.map = ImmutableMap.copyOf(ArgChecker.notNull(map, "map"));
  }

  @SuppressWarnings("unchecked")
  public <T> Optional<T> get(FieldKey<T> key) {
    ArgChecker.notNull(key, "key");
    T value = (T) map.get(key);
    return Optional.ofNullable(value);
  }

  public <T> FieldMap withValues(FieldKey<T> key, T value) {
    ArgChecker.notNull(key, "key");
    ArgChecker.notNull(value, "value");
    return new FieldMap(ImmutableMap.<FieldKey<?>, Object>builder().putAll(map).put(key, value).build());
  }

  // TODO multiple overrides with 2, 3, ... pairs?
  public <T> FieldMap withValues(FieldKey<T> key1, T value1, FieldKey<T> key2, T value2) {
    ArgChecker.notNull(key1, "key1");
    ArgChecker.notNull(value1, "value1");
    ArgChecker.notNull(key2, "key2");
    ArgChecker.notNull(value2, "value2");
    return new FieldMap(ImmutableMap.<FieldKey<?>, Object>builder().putAll(map).put(key1, value1).put(key2, value2).build());
  }

  //------------------------- AUTOGENERATED START -------------------------
  ///CLOVER:OFF
  /**
   * The meta-bean for {@code FieldMap}.
   * @return the meta-bean, not null
   */
  public static FieldMap.Meta meta() {
    return FieldMap.Meta.INSTANCE;
  }

  static {
    JodaBeanUtils.registerMetaBean(FieldMap.Meta.INSTANCE);
  }

  /**
   * Returns a builder used to create an instance of the bean.
   * @return the builder, not null
   */
  public static FieldMap.Builder builder() {
    return new FieldMap.Builder();
  }

  @Override
  public FieldMap.Meta metaBean() {
    return FieldMap.Meta.INSTANCE;
  }

  @Override
  public <R> Property<R> property(String propertyName) {
    return metaBean().<R>metaProperty(propertyName).createProperty(this);
  }

  @Override
  public Set<String> propertyNames() {
    return metaBean().metaPropertyMap().keySet();
  }

  //-----------------------------------------------------------------------
  /**
   * Gets the map.
   * @return the value of the property, not null
   */
  public Map<FieldKey<?>, Object> getMap() {
    return map;
  }

  //-----------------------------------------------------------------------
  /**
   * Returns a builder that allows this bean to be mutated.
   * @return the mutable builder, not null
   */
  public Builder toBuilder() {
    return new Builder(this);
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == this) {
      return true;
    }
    if (obj != null && obj.getClass() == this.getClass()) {
      FieldMap other = (FieldMap) obj;
      return JodaBeanUtils.equal(getMap(), other.getMap());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int hash = getClass().hashCode();
    hash += hash * 31 + JodaBeanUtils.hashCode(getMap());
    return hash;
  }

  @Override
  public String toString() {
    StringBuilder buf = new StringBuilder(64);
    buf.append("FieldMap{");
    int len = buf.length();
    toString(buf);
    if (buf.length() > len) {
      buf.setLength(buf.length() - 2);
    }
    buf.append('}');
    return buf.toString();
  }

  protected void toString(StringBuilder buf) {
    buf.append("map").append('=').append(JodaBeanUtils.toString(getMap())).append(',').append(' ');
  }

  //-----------------------------------------------------------------------
  /**
   * The meta-bean for {@code FieldMap}.
   */
  public static class Meta extends DirectMetaBean {
    /**
     * The singleton instance of the meta-bean.
     */
    static final Meta INSTANCE = new Meta();

    /**
     * The meta-property for the {@code map} property.
     */
    @SuppressWarnings({"unchecked", "rawtypes" })
    private final MetaProperty<Map<FieldKey<?>, Object>> map = DirectMetaProperty.ofImmutable(
        this, "map", FieldMap.class, (Class) Map.class);
    /**
     * The meta-properties.
     */
    private final Map<String, MetaProperty<?>> metaPropertyMap$ = new DirectMetaPropertyMap(
        this, null,
        "map");

    /**
     * Restricted constructor.
     */
    protected Meta() {
    }

    @Override
    protected MetaProperty<?> metaPropertyGet(String propertyName) {
      switch (propertyName.hashCode()) {
        case 107868:  // map
          return map;
      }
      return super.metaPropertyGet(propertyName);
    }

    @Override
    public FieldMap.Builder builder() {
      return new FieldMap.Builder();
    }

    @Override
    public Class<? extends FieldMap> beanType() {
      return FieldMap.class;
    }

    @Override
    public Map<String, MetaProperty<?>> metaPropertyMap() {
      return metaPropertyMap$;
    }

    //-----------------------------------------------------------------------
    /**
     * The meta-property for the {@code map} property.
     * @return the meta-property, not null
     */
    public final MetaProperty<Map<FieldKey<?>, Object>> map() {
      return map;
    }

    //-----------------------------------------------------------------------
    @Override
    protected Object propertyGet(Bean bean, String propertyName, boolean quiet) {
      switch (propertyName.hashCode()) {
        case 107868:  // map
          return ((FieldMap) bean).getMap();
      }
      return super.propertyGet(bean, propertyName, quiet);
    }

    @Override
    protected void propertySet(Bean bean, String propertyName, Object newValue, boolean quiet) {
      metaProperty(propertyName);
      if (quiet) {
        return;
      }
      throw new UnsupportedOperationException("Property cannot be written: " + propertyName);
    }

  }

  //-----------------------------------------------------------------------
  /**
   * The bean-builder for {@code FieldMap}.
   */
  public static class Builder extends DirectFieldsBeanBuilder<FieldMap> {

    private Map<FieldKey<?>, Object> map = new HashMap<FieldKey<?>, Object>();

    /**
     * Restricted constructor.
     */
    protected Builder() {
    }

    /**
     * Restricted copy constructor.
     * @param beanToCopy  the bean to copy from, not null
     */
    protected Builder(FieldMap beanToCopy) {
      this.map = new HashMap<FieldKey<?>, Object>(beanToCopy.getMap());
    }

    //-----------------------------------------------------------------------
    @Override
    public Object get(String propertyName) {
      switch (propertyName.hashCode()) {
        case 107868:  // map
          return map;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
    }

    @SuppressWarnings("unchecked")
    @Override
    public Builder set(String propertyName, Object newValue) {
      switch (propertyName.hashCode()) {
        case 107868:  // map
          this.map = (Map<FieldKey<?>, Object>) newValue;
          break;
        default:
          throw new NoSuchElementException("Unknown property: " + propertyName);
      }
      return this;
    }

    @Override
    public Builder set(MetaProperty<?> property, Object value) {
      super.set(property, value);
      return this;
    }

    @Override
    public Builder setString(String propertyName, String value) {
      setString(meta().metaProperty(propertyName), value);
      return this;
    }

    @Override
    public Builder setString(MetaProperty<?> property, String value) {
      super.setString(property, value);
      return this;
    }

    @Override
    public Builder setAll(Map<String, ? extends Object> propertyValueMap) {
      super.setAll(propertyValueMap);
      return this;
    }

    @Override
    public FieldMap build() {
      return new FieldMap(
          map);
    }

    //-----------------------------------------------------------------------
    /**
     * Sets the {@code map} property in the builder.
     * @param map  the new value, not null
     * @return this, for chaining, not null
     */
    public Builder map(Map<FieldKey<?>, Object> map) {
      JodaBeanUtils.notNull(map, "map");
      this.map = map;
      return this;
    }

    //-----------------------------------------------------------------------
    @Override
    public String toString() {
      StringBuilder buf = new StringBuilder(64);
      buf.append("FieldMap.Builder{");
      int len = buf.length();
      toString(buf);
      if (buf.length() > len) {
        buf.setLength(buf.length() - 2);
      }
      buf.append('}');
      return buf.toString();
    }

    protected void toString(StringBuilder buf) {
      buf.append("map").append('=').append(JodaBeanUtils.toString(map)).append(',').append(' ');
    }

  }

  ///CLOVER:ON
  //-------------------------- AUTOGENERATED END --------------------------
}
